CREATE TABLE `spring_session` (
	`SESSION_ID` CHAR(36) NOT NULL,
	`CREATION_TIME` BIGINT(20) NOT NULL,
	`LAST_ACCESS_TIME` BIGINT(20) NOT NULL,
	`MAX_INACTIVE_INTERVAL` INT(11) NOT NULL,
	`PRINCIPAL_NAME` VARCHAR(512) NULL DEFAULT NULL,
	PRIMARY KEY (`SESSION_ID`),
	INDEX `SPRING_SESSION_IX1` (`LAST_ACCESS_TIME`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `spring_session_attributes` (
	`SESSION_ID` CHAR(36) NOT NULL,
	`ATTRIBUTE_NAME` VARCHAR(200) NOT NULL,
	`ATTRIBUTE_BYTES` BLOB NOT NULL,
	PRIMARY KEY (`SESSION_ID`, `ATTRIBUTE_NAME`),
	INDEX `SPRING_SESSION_ATTRIBUTES_IX1` (`SESSION_ID`),
	CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `spring_session` (`SESSION_ID`) ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
