spring: 
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa_sample
    username: jpa_sample
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  messages:
    basename: i18n/messages
    encoding: UTF-8

  redis:
    host: 192.168.0.156
    port: 6379

logging:
  level:
    org.hibernate.sql: debug
    
server:
  jsp-servlet:
    init-parameters: 
      development: true