# my pc 설정.ㅡ,ㅡ
#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/jpa_sample
#    username: jpa_sample
#    password: 1111

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jmlim_test
    username: jmlim
    password: jmlim1234
  jpa:
    hibernate:
      ddl-auto: update #create
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  messages:
    basename: i18n/messages
    encoding: UTF-8

  redis:
    host: localhost #192.168.0.156
    port: 6379

logging:
  level:
    org.hibernate.sql: debug
    
server:
  port: 8180
  jsp-servlet:
    init-parameters: 
      development: true