spring: 
  datasource:
    url: jdbc:mariadb://localhost:3306/jpasample
    username: jpasample
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    


logging:
  level:
    org.hibernate.sql: debug
    
server:
  jsp-servlet:
    init-parameters: 
      development: true